CREATE TABLE users (
    users_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    users_name TEXT NOT NULL UNIQUE,
    users_password TEXT NOT NULL
);

CREATE TABLE routines (
    routines_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    routines_name TEXT NOT NULL,
    assigned_user INTEGER REFERENCES users(users_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE exercises (
    exercises_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exercises_name TEXT NOT NULL,
    exercises_description TEXT,
    assigned_routine INTEGER REFERENCES routines(routines_id) ON DELETE CASCADE NOT NULL
);